import { Question } from "./API";
export const easyQuestions: Question[] = [
  {
    category: "bible",
    question: "Who came to Jesus at night?",
    correct_answer: "Nicodemus",
    incorrect_answers: ["John","Lazarus","His mother"],
    difficulty: "easy",
    type: "multiple",
  },
  {
    category: "bible",
    question: "Who was the first king of Israel?",
    correct_answer: "Saul",
    incorrect_answers: ["David","Solomon","Jesus"],
    difficulty: "easy",
    type: "multiple",
  },
  {
    category: "bible",
    question: "How many brothers did Joseph have?",
    correct_answer: "11",
    incorrect_answers: ["7","3","12"],
    difficulty: "easy",
    type: "multiple",
  },
  {
    category: "bible",
    question: "What animal did the staff of Moses turn into when he went to confront Pharaoh to let the Israelites go?",
    correct_answer: "Snake",
    incorrect_answers: ["Raven","Pig","Dove"],
    difficulty: "easy",
    type: "multiple",
  },
  {
    category: "bible",
    question: "Who did Abraham have his first child with?",
    correct_answer: "Hagar",
    incorrect_answers: ["Sarah","Mary","Salome"],
    difficulty: "easy",
    type: "multiple",
  },
  {
    category: "bible",
    question: "When did Jesus die?",
    correct_answer: "At the age of 33",
    incorrect_answers: ["At the age of 30","At the age of 25","At the age of 24"],
    difficulty: "easy",
    type: "multiple",
  },
  {
    category: "bible",
    question: "How many books are in the Old Testament?",
    correct_answer: "39",
    incorrect_answers: ["66","36","42"],
    difficulty: "easy",
    type: "multiple",
  },
  {
    category: "bible",
    question: "Where was Saul traveling to when he had a divine encounter and was converted?",
    correct_answer: "Damascus",
    incorrect_answers: ["Jerusalem","Jericho","Bethsaida"],
    difficulty: "easy",
    type: "multiple",
  },
  {
    category: "bible",
    question: "How many books are in the Bible",
    correct_answer: "66",
    incorrect_answers: ["65","69","63"],
    difficulty: "easy",
    type: "multiple",
  },
  {
    category: "bible",
    question: "In which city was Jesus born?",
    correct_answer: "Bethlehem",
    incorrect_answers: ["Nazareth","Jerusalem","Bethany"],
    difficulty: "easy",
    type: "multiple",
  }
];
export const mediumQuestions: Question[] = [
  {
    category: "bible",
    question: "Who requested for the head of John the Baptist?",
    correct_answer: "Salome",
    incorrect_answers: ["Herodias","Herodias's wife","Pharisees"],
    difficulty: "medium",
    type: "multiple",
  },
  {
    category: "bible",
    question: "What were the two plagues that afflicted the Egyptians physically?",
    correct_answer: "Gnats and boils",
    incorrect_answers: ["Gnats and blisters","Boils and hives","Dandruff and hives"],
    difficulty: "medium",
    type: "multiple",
  },
  {
    category: "bible",
    question: "According to the Bible, what weapons was Goliath carrying when he was slain by David?",
    correct_answer: "Spear and Sword",
    incorrect_answers: ["Knife and Rock","Slingshot and Stone","Bow and Arrow"],
    difficulty: "medium",
    type: "multiple",
  },
  {
    category: "bible",
    question: "Which of these domesticated animals is not mentioned in the Bible",
    correct_answer: "Cat",
    incorrect_answers: ["Bird","Dog","Horse"],
    difficulty: "medium",
    type: "multiple",
  },
  {
    category: "bible",
    question: "How many days was Jonah in the belly of the big fish?",
    correct_answer: "Three days and nights",
    incorrect_answers: ["Five days and nights","Seven days and nights","Ten days and nights"],
    difficulty: "medium",
    type: "multiple",
  },
  {
    category: "bible",
    question: "How was Ruth related to Naomi?",
    correct_answer: "Daughter-in-law",
    incorrect_answers: ["Sister","Daughter","Cousin"],
    difficulty: "medium",
    type: "multiple",
  },
  {
    category: "bible",
    question: "In the Book of Judges, what is the name of Samson’s lover who betrays him to the Philistines?",
    correct_answer: "Delilah",
    incorrect_answers: ["Ruth","Esther","Mary"],
    difficulty: "medium",
    type: "multiple",
  },
  {
    category: "bible",
    question: "In the Bible, on what island was Paul shipwrecked?",
    correct_answer: "Malta",
    incorrect_answers: ["Greece","Rhodes","Patmos"],
    difficulty: "medium",
    type: "multiple",
  },
  {
    category: "bible",
    question: "According to the Bible, in what city was David anointed King?",
    correct_answer: "Hebron",
    incorrect_answers: ["Jerusalem","Bethlehem","Rabbah"],
    difficulty: "medium",
    type: "multiple",
  },
  {
    category: "bible",
    question: "Who was the first person to come upon the injured man in the parable of the Good Samaritan? ",
    correct_answer: "Priest",
    incorrect_answers: ["Tax collector","Innkeeper","Judge"],
    difficulty: "medium",
    type: "multiple",
  }
];
export const hardQuestions: Question[] = [
  {
    category: "bible",
    question: "How many people did Noah’s ark carry?",
    correct_answer: "Eight",
    incorrect_answers: ["Six","Five","Ten"],
    difficulty: "hard",
    type: "multiple",
  },
  {
    category: "bible",
    question: "What piece of clothing made Joseph's brothers jealous? ",
    correct_answer: "Coat",
    incorrect_answers: ["Shoes","Belt","Special headpiece"],
    difficulty: "hard",
    type: "multiple",
  },
  {
    category: "bible",
    question: "How many of each animal did Moses bring into the Ark? ",
    correct_answer: "None",
    incorrect_answers: ["678","360","366"],
    difficulty: "hard",
    type: "multiple",
  },
  {
    category: "bible",
    question: "What book of the Bible do you find Lydia of Thyatira's story?",
    correct_answer: "Acts",
    incorrect_answers: ["Colossians","Proverbs","Isiah"],
    difficulty: "hard",
    type: "multiple",
  },
  {
    category: "bible",
    question: "What name was given to the Jewish ruling council that plotted Jesus’ death?",
    correct_answer: "The Sanhedrin",
    incorrect_answers: ["The Herodians","Pharisees","Sadducees"],
    difficulty: "hard",
    type: "multiple",
  },
  {
    category: "bible",
    question: "How long did Enoch live?",
    correct_answer: "430",
    incorrect_answers: ["390","395","360"],
    difficulty: "hard",
    type: "multiple",
  },
  {
    category: "bible",
    question: "At what age did Sarah, the wife of Abraham, die?",
    correct_answer: "127",
    incorrect_answers: ["100","110","132"],
    difficulty: "hard",
    type: "multiple",
  },
  {
    category: "bible",
    question: "In Luke, the woman cleans Jesus feet with what two things? ",
    correct_answer: "Tears and her hair",
    incorrect_answers: ["Soap and water","Water and a towel","Tears and a towel"],
    difficulty: "hard",
    type: "multiple",
  },
  {
    category: "bible",
    question: " Which book of the Bible mentioned Haman?",
    correct_answer: "Esther",
    incorrect_answers: ["Jeremiah","Luke","Acts"],
    difficulty: "hard",
    type: "multiple",
  },
  {
    category: "bible",
    question: "What is the longest book in the Bible?",
    correct_answer: "Psalm",
    incorrect_answers: ["Genesis","Exodus","Songs of Solomon"],
    difficulty: "hard",
    type: "multiple",
  },
];
